from myqueue.job import Job


def workflow():
    return [
        Job('h2o.py', folder='water'),
        Job('CO.py@8x15s', folder='wavefunctions'),
        Job('Al_fcc.py@2x15s', folder='aluminium'),
        Job('Al_bcc.py@2x15s', folder='aluminium'),
        Job('Al_fcc_vs_bcc.py@2x15s', folder='aluminium'),
        Job('Al_fcc_modified.py@2x15s', folder='aluminium'),
        Job('initial.py@2x15s', folder='diffusion'),
        Job('solution.py@2x15s', folder='diffusion'),
        Job('densitydiff.py', folder='diffusion', deps=['solution.py']),
        Job('si.py@8x15s', folder='wannier'),
        Job('wannier-si.py', folder='wannier', deps=['si.py']),
        Job('benzene.py@8x15s', folder='wannier'),
        Job('wannier-benzene.py', folder='wannier', deps=['benzene.py']),
        Job('ag.py', folder='band_structure'),
        Job('h2o.py@8x15s', folder='vibrations'),
        Job('H2O_vib.py@8x15s', folder='vibrations', deps=['h2o.py']),
        Job('H2O_vib_2.py@4x15s', folder='vibrations', deps=['H2O_vib.py']),
        Job('ferro.py@4x15s', folder='iron'),
        Job('anti.py@4x15s', folder='iron'),
        Job('non.py@2x15s', folder='iron'),
        Job('PBE.py', folder='iron', deps=['ferro.py', 'anti.py', 'non.py']),
        Job('test.py', folder='eels', deps=['../band_structure/ag.py']),
        Job('test.py', folder='gw'),
        Job('si.pbe.py', folder='rpa'),
        Job('si_pbe_exx.py@4x15s', folder='rpa', deps=['si.pbe.py']),
        Job('si.rpa_init_pbe.py', folder='rpa'),
        Job('si.rpa.py@4x15s', folder='rpa', deps=['si.rpa_init_pbe.py']),
        Job('con_pw.py', folder='stress'),
        Job('stress.py', folder='stress'),
        Job('pt_h2_tb_transport.py', folder='transport'),
        Job('pt_h2_lcao_manual.py', folder='transport'),
        Job('pt_h2_lcao_transport.py', folder='transport',
            deps=['pt_h2_lcao_manual.py'])]
