version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - graphviz
    - povray
  jobs:
    pre_install:
      - |
        cat << EOF > siteconfig.py
        mpi = False
        noblas = True
        nolibxc = True
        EOF
    pre_build:
      - gpaw-setup H
      - gpaw-setup C
      - echo $PWD
      - echo $HOME
      - mkdir $HOME/.gpaw
      - |
        cat << EOF > $HOME/.gpaw/rc.py
        setup_paths[:] = ["/home/docs/checkouts/readthedocs.org/user_builds/gpaw/checkouts/latest"]
        EOF

sphinx:
  configuration: doc/conf.py

python:
  install:
    - requirements: doc/requirements.txt
    - method: pip
      path: .
