def erf(x: float) -> float: ...
def cerf(x: complex) -> complex: ...
def adjust_positions() -> None: ...
def adjust_momenta() -> None: ...
def calculate_forces_H2O() -> None: ...
def localize() -> None: ...
def spherical_harmonics() -> None: ...
def hartree() -> None: ...
def pack() -> None: ...
