#!/usr/bin/env python
# Emacs: treat this as -*- python -*-

import gpaw
from gpaw.wavefunctions.pw import PW
from gpaw.occupations import FermiDirac, MethfesselPaxton
from gpaw.mixer import Mixer, MixerSum, MixerDif
from gpaw.poisson import PoissonSolver
from gpaw.eigensolvers import RMM_DIIS
from ase.asec import main


class calculator:
    name = 'gpaw'
    namespace = {'PW': PW,
                 'FermiDirac': FermiDirac,
                 'MethfesselPaxton': MethfesselPaxton,
                 'Mixer': Mixer,
                 'MixerSum': MixerSum,
                 'MixerDif': MixerDif,
                 'PoissonSolver': PoissonSolver,
                 'RMM_DIIS': RMM_DIIS}

main(calculator)
