#!/usr/bin/env python

from __future__ import print_function
import os
import fnmatch
import urllib2
from StringIO import StringIO
import tarfile
from optparse import OptionParser


usage = '%prog [OPTION] [DIR]'
description = ('Download and install gpaw-setups into '
               'DIR/gpaw-setups-[version] if DIR is specified, '
               'otherwise print current GPAW setup search paths.')


p = OptionParser(usage=usage, description=description)
p.add_option('--package', metavar='URL',
             help='download PACKAGE of setups or pseudopotentials.  '
             'Run without arguments to display a list of versions.  '
             'VERSION can be the full URL or a part such as  '
             '\'0.8\', \'0.6.6300\', or \'sg15\'.')
p.add_option('--tarball', metavar='FILENAME',
             help='unpack and install from local tarball FILENAME '
             'instead of downloading from the GPAW website')
opts, args = p.parse_args()
nargs = len(args)


def get_setup_file_urls():
    setups_page = 'https://wiki.fysik.dtu.dk/gpaw/_sources/setups/setups.txt'
    response = urllib2.urlopen(setups_page)
    pattern = 'https://wiki.fysik.dtu.dk/gpaw-files/gpaw-setups-*.tar.gz'
    urls = [line.strip() for line in response
            if fnmatch.fnmatch(line.strip(), pattern)]
    return urls

sg15_page = 'http://fpmd.ucdavis.edu/qso/potentials/sg15_oncv/'
sg15_file = 'sg15_oncv_upf_2015-01-24.tar.gz'
sg15_url = ''.join([sg15_page, sg15_file])

# The sg15 file is a tarbomb.  We will later defuse it by untarring
# into a subdirectory, so we don't leave a ghastly mess on the
# unsuspecting user's system.

if not opts.tarball:
    urls = get_setup_file_urls()
    urls.append(sg15_url)

    def print_urls(urls, marked=None):
        for url in urls:
            pageurl, fname = url.rsplit('/', 1)
            #print(pageurl, fname)
            domain = pageurl.split('//', 1)[1].split('/', 1)[0]
            if url == marked:
                marking = ' [*]'
                #print(' [*] %s [%s]' % (fname, domain))
            else:
                marking = '    '
            print(' %s %s [%s]' % (marking, fname, domain))

    if len(urls) == 0:
        p.error('For some reason, no setup packages were found.  Probably'
                'this script is out of date.  Please rummage around GPAW '
                'web page until solution is found.')

    if opts.package:
        matching_urls = [url for url in urls if opts.package in url]
        if len(matching_urls) > 1:
            p.error('More than one setup file matches version "%s":\n'
                    '%s' % (opts.package, '\n'.join(matching_urls)))
        elif len(matching_urls) == 0:
            p.error('\nNo setup matched the specified version "%s".\n'
                    'Available setups are:\n'
                    '%s' % (opts.package, '\n'.join(urls)))
        assert len(matching_urls) == 1
        url = matching_urls[0]
    else:
        url = urls[0]

    print('Available setups and pseudopotentials')
    print_urls(urls, url)
    print()

def print_setups_info():
    try:
        import gpaw
    except ImportError, e:
        p.error("Cannot import 'gpaw'.  GPAW does not appear to be installed."
                " %s" % e)
    npaths = len(gpaw.setup_paths)
    if npaths == 0:
        print('GPAW currently has no setup search paths')
    else:
        print('GPAW setup paths in order of search priority:')
        for path in gpaw.setup_paths:
            print('     %s' % path)

if nargs == 0:
    print_setups_info()
    print()
    progname = p.get_prog_name()
    print('Run %s DIR to install newest setups into DIR.' % progname)
    print('Run %s DIR --package=PACKAGE to install PACKAGE (from above).'
          % progname)
    print('See %s --help for more info.' % progname)
    raise SystemExit
elif len(args) != 1:
    p.error('No more than one DIR expected.  Please try --help.')


targetpath = args[0]


if opts.tarball:
    print('Reading local tarball %s' % opts.tarball)
    targzfile = tarfile.open(opts.tarball)
    tarfname = opts.tarball
else:
    tarfname = url.rsplit('/', 1)[1]
    print('Selected %s.  Downloading...' % tarfname)
    response = urllib2.urlopen(url)
    targzfile = tarfile.open(fileobj=StringIO(response.read()))


if not os.path.exists(targetpath):
    os.makedirs(targetpath)

setup_dirname = tarfname.rsplit('.', 2)[0]  # remove .tar.gz ending
setup_path = os.path.abspath(os.path.join(targetpath, setup_dirname))
if tarfname == sg15_file and not os.path.isdir(setup_path):
    # Defuse tarbomb
    os.mkdir(setup_path)
    targetpath = os.path.join(targetpath, setup_dirname)

print('Extracting tarball into %s' % targetpath)
targzfile.extractall(targetpath)
assert os.path.isdir(setup_path)


# Okay, now we have to maybe edit people's rc files.
rcfiledir = os.path.join(os.environ['HOME'], '.gpaw')
rcfilepath = os.path.join(rcfiledir, 'rc.py')


print('Setups installed into %s.' % setup_path)


# We could do all this by importing the rcfile as well and checking
# whether things are okay or not.
rcline1 = 'from gpaw import setup_paths'
rcline2 = "setup_paths.insert(0, '%s')" % setup_path


answer = raw_input('Register this setup path in %s? [y/n] ' % rcfilepath)


if answer.lower() == 'y':
    # First we create the file
    if not os.path.exists(rcfiledir):
        os.makedirs(rcfiledir)
    if not os.path.exists(rcfilepath):
        tmpfd = open(rcfilepath, 'w')  # Just create empty file
        tmpfd.close()

    for line in open(rcfilepath):
        if line.startswith(rcline2):
            print('It looks like the path is already registered in %s.'
                  % rcfilepath)
            print('File will not be modified at this time.')
            break
    else:
        rcfd = open(rcfilepath, 'a')
        print(rcline1, file=rcfd)
        print(rcline2, file=rcfd)
        print('Setup path has been registered in %s.' % rcfilepath)
else:
    if answer.lower() != 'n':
        print('What do you mean by "%s"?  Assuming "n".' % answer)
    else:
        print('As you wish.')
    print('You can manually write the following two lines to %s:' % rcfilepath)
    print()
    print(rcline1)
    print(rcline2)
    print()
print('Installation complete.')
