def agts(queue):
    gs_H_lda = queue.add('H.ralda_01_lda.py', ncpus=2, walltime=5)
    queue.add('H.ralda_02_rpa_at_lda.py', deps=gs_H_lda, ncpus=16, walltime=20)
    queue.add('H.ralda_03_ralda.py', deps=gs_H_lda, ncpus=16, walltime=200)
    gs_H_pbe = queue.add('H.ralda_04_pbe.py', ncpus=2, walltime=5)
    queue.add('H.ralda_05_rpa_at_pbe.py', deps=gs_H_pbe, ncpus=16, walltime=20)
    queue.add('H.ralda_06_rapbe.py', deps=gs_H_pbe, ncpus=16, walltime=200)
    gs_CO = queue.add('gs_CO.py', ncpus=1, walltime=1000)
    queue.add('rapbe_CO.py', deps=gs_CO, ncpus=16, walltime=2000)
    gs_diamond = queue.add('gs_diamond.py', deps=gs_CO, ncpus=1, walltime=100)
    queue.add('rapbe_diamond.py', deps=gs_diamond, ncpus=16, walltime=1200)
